### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by YuKitsune** [pierr3/UACPlugin#1]
Been a while since this repo was last updated, wanted to try and contribute. But i'm having an issue building.

![Build Errors](https://image.prntscr.com/image/0lyf2zFvSmqIAkusdOfELQ.png)

Any ideas?

**Comment by pierr3** [comment]
Seems to be related to EuroScopePlugInDll.lib, did you include it properly?

**Comment by YuKitsune** [comment]
I just followed the EuroScope doc showing how to set up the environment, not sure if there is anything different that needs to be done.

**Comment by pierr3** [comment]
Then that should be good, try fiddling with your compilation settings, I'll see on my end if I can get it to build.

**Comment by pierr3** [comment]
I've updated the build config, and the project now builds fine on appveyor, make sure you're compiling with the x86 Release or Debug profile in the project

**Comment by YuKitsune** [comment]
Works like a charm!
